/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.iu;

import javax.vecmath.Vector3d;
import jmr.result.Vector;

/**
 *
 * @author alejandro
 */
public class NewJPanel extends Abstract3DPanel {

    /**
     * Creates new form NewJPanel
     */
    
    private int numDesc;
    public NewJPanel() {
      
        super();
        
        planeActive = true;
        
    }
 
    @Override
    protected void createScene() {
  
        numDesc = getVector(0).dimension();

        
        Vector3d v = new Vector3d(0,0,0);
        
        drawImage(getResultMetada(0), v);
        
        
        double geoMean = getGeometricMean();
        
        double variance = getVariance();

        updateInfo(geoMean, variance);
        
       // System.out.println("geoMean: " + geoMean + " - variance: " + variance);
      
        double x = 0;
        double y = 0;
        double valGeo = 0;

        double valVariance = 0;
        double aux1 = 0;
        double aux2 = 0;
        
        for(int i = 1; i < results.size(); i++){

            double vMean = getMean(getVector(i));
            aux1 = 0;
            aux2 = 0;
            
            for(int j = 0; j < numDesc; j++){
                
                // Calculo la media geometrica para una imagen
               
                aux1 += Math.log(getVector(i).coordinate(j));
                
                // Calculo la varianza
                
                aux2 += (getVector(i).coordinate(j) - vMean) * 
                        (getVector(i).coordinate(j) - vMean);
     
            }
            

            valGeo =  Math.exp(aux1/numDesc);

            valVariance = aux2/numDesc;
            
            x = Math.abs(geoMean - valGeo);
            
            y = Math.abs(variance - valVariance);
            
            System.out.println("x: " + x + " y: " + y);
            System.out.println("valGeo: " + valGeo + " - valVariance: " + valVariance);
            
            System.out.println();
            
            v.x = x * 150;
            //v.x = x*50;
            v.y += 2;
            v.z = y*150;
            
           // System.out.println(v);
            
            drawImage(getResultMetada(i), v);
            
        }

        
    }

    @Override
    protected void sceneControl() {
        
    }

    @Override
    protected void drawPosition(Vector3d pos, int index) {
        
    }
    
    private double getGeometricMean() {
        
        double gm_log = 0;
        
        
        int n = results.size() * numDesc;

        
        for(int i = 1; i < results.size(); i++){
            for(int j = 0; j < numDesc; j++){
                gm_log += Math.log(getVector(i).coordinate(j));
            }
        }        
        
        return Math.exp(gm_log/n);
    }
    
    private double getMean(){
        
        double sum = 0;

        int n = results.size() * numDesc;

        
        for(int i = 1; i < results.size(); i++){
            for(int j = 0; j < numDesc; j++){
                sum += getVector(i).coordinate(j);
            }
        }

        return sum/n;
        
    }
    
    private double getMean(Vector vec){

        double sum = 0;
        for(int i = 0; i < numDesc; i++){
            sum += vec.coordinate(i);
        }
        
        return sum/numDesc;
    }
    
    private double getVariance(){

        double mean = getMean(); 

        int n = results.size() * numDesc;
        double sum = 0;

        for(int i = 1; i < results.size(); i++){
            for(int j = 0; j < numDesc; j++){
                double value = getVector(i).coordinate(j);
                sum += (value-mean)*(value-mean);
            }
        }
        
        return sum/n;
         
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
