/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.iu;

import com.sun.j3d.utils.behaviors.vp.OrbitBehavior;
import com.sun.j3d.utils.universe.SimpleUniverse;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GraphicsConfiguration;
import javax.media.j3d.BoundingSphere;
import javax.media.j3d.BranchGroup;
import javax.media.j3d.Canvas3D;
import javax.media.j3d.TransformGroup;
import javax.vecmath.Point3d;
import javax.vecmath.Vector3f;
import jmr.result.ResultList;
import static jmr.iu.AbstractVisualizationPanel.DEFAULT_COMMON_SIZE;

/**
 *
 * @author alejandro
 */
public class SecuencialPanel extends AbstractVisualizationPanel {

    /**
     * Creates new form SecuencialPanel
     */
    
    private Canvas3D can3D;
    
    public SecuencialPanel() {
        initComponents();
        System.out.println("ESTOY EN EL CONSTRUCTOR");
        initialize(canvas3D);
    }
    
    
    public SecuencialPanel(ResultList list){
        super(list);        
    }
    
    @Override
    public void add(ResultList list){
        super.add(list);
        setBranchGroup(createScene());
        
    }
    
    @Override
    public BranchGroup createScene() {

        Vector3f vector = new Vector3f(0.0f,0.0f,0.0f);
        
        float leftPos = 0.0f;
        float rightPos = 0.0f;
        float yPos = 0.0f;
        
        
        drawImage(getImage(0),vector,0);
        
        
        for(int i = 1; i < results.size(); i++){
            
            if(i%2 != 0){
                rightPos += 1.5;
                vector.x = rightPos;
                
            }
            
            else{
                leftPos -= 1.5;

                vector.x = leftPos;
               
      
            }
            
            yPos -= 0.03;
            vector.y = yPos;
            
            drawImage(getImage(i),vector,i);


        }
        
        return this.objRoot;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

