/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmr.iu;

import com.sun.j3d.utils.behaviors.vp.OrbitBehavior;
import javax.media.j3d.BoundingSphere;
import javax.vecmath.Point3d;
import javax.vecmath.Vector3d;
import jmr.result.ResultList;

/**
 *
 * @author alejandro
 */
public class SpiralPanel extends Abstract3DPanel {

    /**
     * Creates new form SpiralVisualization
     */
    
    private Vector3d vector;
    
    private final float Zdecrement = 0.025f;
    
    
    public SpiralPanel() {  

        super();
        
        
        TYPE = SPIRAL;


    }
    
    public SpiralPanel(ResultList list){
        super(list);
    }
    
    @Override
    public void add(ResultList list){
        super.add(list);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void createScene() {
        
        this.vector = new Vector3d(0.0f,0.0f,0.0f);

        int image = 0;
        
        boolean cont = true;
        
        int maxLoop1 = 3; // +1
         
        int maxLoop2 = 1; // +2
         
        int maxLoop3 = 3; // +2
          
        int maxLoop4 = 2; // +2 
         
        while ((cont))
        {
            
            //First loop
            
            int i=1;
            while(i <=maxLoop1 && cont){

                if(image == 0){
                    drawImage(getResultMetada(image),this.vector);
                }
                
                else{
                    this.vector.x +=1.1;
                    this.vector.z -=Zdecrement;
                    drawImage(getResultMetada(image),this.vector);
                    
                 //   System.out.println("Imagen numero : " + image + " Valor de z: " + this.vector.z);

                }
                
                image++;
                i++;
                
                if(image >= this.results.size())
                    cont=false;
            }
                        
            // Second loop
            
            i=1;
            while(i <=maxLoop2 && cont){
                
                this.vector.y -= 1.1;
                this.vector.z -=Zdecrement;
                drawImage(getResultMetada(image),this.vector);
                
                image++;
                i++;
               // System.out.println("Imagen numero : " + image + " Valor de z: " + this.vector.z);
                
                if(image >= this.results.size())
                    cont=false;
  
            }
            
            // Third loop
            
            i=1;
            while(i <= maxLoop3 && cont){
                
                this.vector.x -= 1.1;
                this.vector.z -=Zdecrement;
                drawImage(getResultMetada(image),this.vector);
                
                image++;
                i++;
                // System.out.println("Imagen numero : " + image + " Valor de z: " + this.vector.z);
                if(image >= this.results.size())
                    cont=false;
            }
            
            // Fourth loop
            
            i=1;
            while(i <= maxLoop4 && cont){
                
                this.vector.y += 1.1;
                this.vector.z -=Zdecrement;
                drawImage(getResultMetada(image),this.vector);
                
                image++;
                i++;
              //   System.out.println("Imagen numero : " + image + " Valor de z: " + this.vector.z);
                if(image >= this.results.size())
                    cont=false;
            }
            
            
            if(maxLoop1 == 3){
                maxLoop1++;
            }
            
            else{
                maxLoop1+=2;
            }
            
            maxLoop2+=2;
            maxLoop3+=2;
            maxLoop4+=2;

        }
    
    }

    @Override
    public void mouseControl() {

        BoundingSphere bounds =
        new BoundingSphere(new Point3d(0.0, 0.0, 0.0), 1000000000000.0);
     
        m_orbit = new OrbitBehavior(canvas3d, 
        OrbitBehavior.REVERSE_ALL | OrbitBehavior.STOP_ZOOM);
      
        

        m_orbit.setRotYFactor(0);
        m_orbit.setRotationCenter(new Point3d(1.0,0,0));
        m_orbit.setSchedulingBounds(bounds);
        m_orbit.setZoomFactor(-1d);
        
        this.simpleU.getViewingPlatform().setNominalViewingTransform();
        
        simpleU.getViewingPlatform().setViewPlatformBehavior(m_orbit);


    }

    @Override
    protected void drawPosition(Vector3d pos, int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected void sceneControl() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


